In [27]:
#Declare model
from keras.models import Sequential
model = Sequential()

In [28]:
#Add layers to the model
from keras.layers import Dense
model.add(Dense(units=4, activation='sigmoid', input_dim=3))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 4)                 16        
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 5         
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [29]:
#Compile the model
from keras import optimizers
sgd= optimizers.SGD(lr=1)
model.compile(loss='mean_squared_error',optimizer=sgd)

In [30]:
#Prepare the input dataset
import numpy as np
np.random.seed(9)
X=np.array([[0,0,1],
           [0,1,1],
           [1,0,1],
           [1,1,1]])
y=np.array([[0],[1],[1],[0]])
print(X,y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] [[0]
 [1]
 [1]
 [0]]


In [31]:
#Train the model
model.fit(X,y,epochs=1500)

Epoch 1/1500
4/4 [==============================] - 0s 120ms/step - loss: 0.3444
Epoch 2/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.3220
Epoch 3/1500
4/4 [==============================] - 0s 0us/step - loss: 0.3008
Epoch 4/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2831
Epoch 5/1500
4/4 [==============================] - 0s 873us/step - loss: 0.2701
Epoch 6/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2616
Epoch 7/1500
4/4 [==============================] - 0s 294us/step - loss: 0.2565
Epoch 8/1500
4/4 [==============================] - 0s 748us/step - loss: 0.2536
Epoch 9/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2520
Epoch 10/1500
4/4 [==============================] - 0s 722us/step - loss: 0.2511
Epoch 11/1500
4/4 [==============================] - 0s 878us/step - loss: 0.2506
Epoch 12/1500
4/4 [==============================] - 0s 249us/step - loss: 0.2504
Epoch 13/1500
4/4 [================

Epoch 102/1500
4/4 [==============================] - 0s 644us/step - loss: 0.2494
Epoch 103/1500
4/4 [==============================] - 0s 353us/step - loss: 0.2494
Epoch 104/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2494
Epoch 105/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2494
Epoch 106/1500
4/4 [==============================] - 0s 681us/step - loss: 0.2494
Epoch 107/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2494
Epoch 108/1500
4/4 [==============================] - 0s 919us/step - loss: 0.2494
Epoch 109/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2494
Epoch 110/1500
4/4 [==============================] - 0s 507us/step - loss: 0.2494
Epoch 111/1500
4/4 [==============================] - 0s 653us/step - loss: 0.2493
Epoch 112/1500
4/4 [==============================] - 0s 657us/step - loss: 0.2493
Epoch 113/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2493
Epoch 114/1500

Epoch 202/1500
4/4 [==============================] - 0s 666us/step - loss: 0.2480
Epoch 203/1500
4/4 [==============================] - 0s 446us/step - loss: 0.2480
Epoch 204/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2480
Epoch 205/1500
4/4 [==============================] - 0s 488us/step - loss: 0.2479
Epoch 206/1500
4/4 [==============================] - 0s 498us/step - loss: 0.2479
Epoch 207/1500
4/4 [==============================] - 0s 647us/step - loss: 0.2479
Epoch 208/1500
4/4 [==============================] - 0s 911us/step - loss: 0.2479
Epoch 209/1500
4/4 [==============================] - 0s 502us/step - loss: 0.2478
Epoch 210/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2478
Epoch 211/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2478
Epoch 212/1500
4/4 [==============================] - 0s 994us/step - loss: 0.2478
Epoch 213/1500
4/4 [==============================] - 0s 446us/step - loss: 0.2477
Epoch 214/

Epoch 302/1500
4/4 [==============================] - 0s 668us/step - loss: 0.2433
Epoch 303/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2432
Epoch 304/1500
4/4 [==============================] - 0s 459us/step - loss: 0.2432
Epoch 305/1500
4/4 [==============================] - 0s 499us/step - loss: 0.2431
Epoch 306/1500
4/4 [==============================] - 0s 421us/step - loss: 0.2430
Epoch 307/1500
4/4 [==============================] - 0s 648us/step - loss: 0.2429
Epoch 308/1500
4/4 [==============================] - 0s 758us/step - loss: 0.2428
Epoch 309/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2427
Epoch 310/1500
4/4 [==============================] - 0s 569us/step - loss: 0.2426
Epoch 311/1500
4/4 [==============================] - 0s 652us/step - loss: 0.2426
Epoch 312/1500
4/4 [==============================] - 0s 499us/step - loss: 0.2425
Epoch 313/1500
4/4 [==============================] - 0s 937us/step - loss: 0.2424
Epoch 31

Epoch 402/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2289
Epoch 403/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2287
Epoch 404/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.2285
Epoch 405/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.2283
Epoch 406/1500
4/4 [==============================] - 0s 813us/step - loss: 0.2280
Epoch 407/1500
4/4 [==============================] - 0s 877us/step - loss: 0.2278
Epoch 408/1500
4/4 [==============================] - 0s 596us/step - loss: 0.2276
Epoch 409/1500
4/4 [==============================] - 0s 802us/step - loss: 0.2273
Epoch 410/1500
4/4 [==============================] - 0s 765us/step - loss: 0.2271
Epoch 411/1500
4/4 [==============================] - 0s 754us/step - loss: 0.2268
Epoch 412/1500
4/4 [==============================] - 0s 421us/step - loss: 0.2266
Epoch 413/1500
4/4 [==============================] - 0s 497us/step - loss: 0.2264
Epoch 414/15

Epoch 502/1500
4/4 [==============================] - 0s 499us/step - loss: 0.1986
Epoch 503/1500
4/4 [==============================] - 0s 768us/step - loss: 0.1982
Epoch 504/1500
4/4 [==============================] - 0s 440us/step - loss: 0.1979
Epoch 505/1500
4/4 [==============================] - 0s 498us/step - loss: 0.1975
Epoch 506/1500
4/4 [==============================] - 0s 631us/step - loss: 0.1971
Epoch 507/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.1967
Epoch 508/1500
4/4 [==============================] - 0s 750us/step - loss: 0.1964
Epoch 509/1500
4/4 [==============================] - 0s 915us/step - loss: 0.1960
Epoch 510/1500
4/4 [==============================] - 0s 555us/step - loss: 0.1956
Epoch 511/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.1952
Epoch 512/1500
4/4 [==============================] - 0s 498us/step - loss: 0.1949
Epoch 513/1500
4/4 [==============================] - 0s 606us/step - loss: 0.1945
Epoch 51

Epoch 602/1500
4/4 [==============================] - 0s 3ms/step - loss: 0.1534
Epoch 603/1500
4/4 [==============================] - 0s 828us/step - loss: 0.1529
Epoch 604/1500
4/4 [==============================] - 0s 597us/step - loss: 0.1523
Epoch 605/1500
4/4 [==============================] - 0s 499us/step - loss: 0.1517
Epoch 606/1500
4/4 [==============================] - 0s 978us/step - loss: 0.1511
Epoch 607/1500
4/4 [==============================] - 0s 583us/step - loss: 0.1505
Epoch 608/1500
4/4 [==============================] - 0s 455us/step - loss: 0.1499
Epoch 609/1500
4/4 [==============================] - 0s 787us/step - loss: 0.1493
Epoch 610/1500
4/4 [==============================] - 0s 412us/step - loss: 0.1487
Epoch 611/1500
4/4 [==============================] - 0s 881us/step - loss: 0.1481
Epoch 612/1500
4/4 [==============================] - 0s 249us/step - loss: 0.1475
Epoch 613/1500
4/4 [==============================] - 0s 916us/step - loss: 0.1469
Epoch 

Epoch 702/1500
4/4 [==============================] - 0s 727us/step - loss: 0.0866
Epoch 703/1500
4/4 [==============================] - 0s 250us/step - loss: 0.0860
Epoch 704/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0854
Epoch 705/1500
4/4 [==============================] - 0s 644us/step - loss: 0.0847
Epoch 706/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0841
Epoch 707/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0835
Epoch 708/1500
4/4 [==============================] - 0s 673us/step - loss: 0.0828
Epoch 709/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0822
Epoch 710/1500
4/4 [==============================] - 0s 460us/step - loss: 0.0816
Epoch 711/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0810
Epoch 712/1500
4/4 [==============================] - 0s 855us/step - loss: 0.0803
Epoch 713/1500
4/4 [==============================] - 0s 611us/step - loss: 0.0797
Epoch 714/1500

Epoch 802/1500
4/4 [==============================] - 0s 450us/step - loss: 0.0408
Epoch 803/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0405
Epoch 804/1500
4/4 [==============================] - 0s 756us/step - loss: 0.0402
Epoch 805/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0400
Epoch 806/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0397
Epoch 807/1500
4/4 [==============================] - 0s 497us/step - loss: 0.0394
Epoch 808/1500
4/4 [==============================] - 0s 3ms/step - loss: 0.0391
Epoch 809/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0389
Epoch 810/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0386
Epoch 811/1500
4/4 [==============================] - 0s 596us/step - loss: 0.0383
Epoch 812/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0381
Epoch 813/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0378
Epoch 814/1500
4/4 [

Epoch 903/1500
4/4 [==============================] - 0s 492us/step - loss: 0.0223
Epoch 904/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0222
Epoch 905/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0220
Epoch 906/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0219
Epoch 907/1500
4/4 [==============================] - 0s 673us/step - loss: 0.0218
Epoch 908/1500
4/4 [==============================] - 0s 498us/step - loss: 0.0217
Epoch 909/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0216
Epoch 910/1500
4/4 [==============================] - 0s 510us/step - loss: 0.0215
Epoch 911/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0214
Epoch 912/1500
4/4 [==============================] - 0s 763us/step - loss: 0.0213
Epoch 913/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0212
Epoch 914/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0211
Epoch 915/1500
4/4

Epoch 1003/1500
4/4 [==============================] - 0s 819us/step - loss: 0.0144
Epoch 1004/1500
4/4 [==============================] - 0s 584us/step - loss: 0.0143
Epoch 1005/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0142
Epoch 1006/1500
4/4 [==============================] - 0s 0us/step - loss: 0.0142
Epoch 1007/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0141
Epoch 1008/1500
4/4 [==============================] - 0s 547us/step - loss: 0.0141
Epoch 1009/1500
4/4 [==============================] - 0s 250us/step - loss: 0.0140
Epoch 1010/1500
4/4 [==============================] - 0s 880us/step - loss: 0.0140
Epoch 1011/1500
4/4 [==============================] - 0s 668us/step - loss: 0.0139
Epoch 1012/1500
4/4 [==============================] - 0s 741us/step - loss: 0.0139
Epoch 1013/1500
4/4 [==============================] - 0s 759us/step - loss: 0.0138
Epoch 1014/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0138


Epoch 1102/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0103
Epoch 1103/1500
4/4 [==============================] - 0s 702us/step - loss: 0.0103
Epoch 1104/1500
4/4 [==============================] - 0s 800us/step - loss: 0.0102
Epoch 1105/1500
4/4 [==============================] - 0s 748us/step - loss: 0.0102
Epoch 1106/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0102
Epoch 1107/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0101
Epoch 1108/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 1109/1500
4/4 [==============================] - 0s 811us/step - loss: 0.0101
Epoch 1110/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0101
Epoch 1111/1500
4/4 [==============================] - 0s 560us/step - loss: 0.0100
Epoch 1112/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0100
Epoch 1113/1500
4/4 [==============================] - 0s 806us/step - loss: 0.0100
Epoc

Epoch 1201/1500
4/4 [==============================] - 0s 273us/step - loss: 0.0079
Epoch 1202/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0079
Epoch 1203/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0079
Epoch 1204/1500
4/4 [==============================] - 0s 621us/step - loss: 0.0078
Epoch 1205/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0078
Epoch 1206/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0078
Epoch 1207/1500
4/4 [==============================] - 0s 860us/step - loss: 0.0078
Epoch 1208/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0078
Epoch 1209/1500
4/4 [==============================] - 0s 610us/step - loss: 0.0077
Epoch 1210/1500
4/4 [==============================] - 0s 634us/step - loss: 0.0077
Epoch 1211/1500
4/4 [==============================] - 0s 511us/step - loss: 0.0077
Epoch 1212/1500
4/4 [==============================] - 0s 395us/step - loss: 0.0077
Ep

Epoch 1300/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0063
Epoch 1301/1500
4/4 [==============================] - 0s 812us/step - loss: 0.0063
Epoch 1302/1500
4/4 [==============================] - 0s 580us/step - loss: 0.0063
Epoch 1303/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0063
Epoch 1304/1500
4/4 [==============================] - 0s 627us/step - loss: 0.0063
Epoch 1305/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0063
Epoch 1306/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0063
Epoch 1307/1500
4/4 [==============================] - 0s 752us/step - loss: 0.0063
Epoch 1308/1500
4/4 [==============================] - 0s 648us/step - loss: 0.0062
Epoch 1309/1500
4/4 [==============================] - 0s 559us/step - loss: 0.0062
Epoch 1310/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0062
Epoch 1311/1500
4/4 [==============================] - 0s 1ms/step - loss: 0.0062
Epoc

Epoch 1399/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 1400/1500
4/4 [==============================] - 0s 2ms/step - loss: 0.0053
Epoch 1401/1500
4/4 [==============================] - 0s 830us/step - loss: 0.0053
Epoch 1402/1500
4/4 [==============================] - 0s 599us/step - loss: 0.0052
Epoch 1403/1500
4/4 [==============================] - 0s 794us/step - loss: 0.0052
Epoch 1404/1500
4/4 [==============================] - 0s 761us/step - loss: 0.0052
Epoch 1405/1500
4/4 [==============================] - 0s 652us/step - loss: 0.0052
Epoch 1406/1500
4/4 [==============================] - 0s 612us/step - loss: 0.0052
Epoch 1407/1500
4/4 [==============================] - 0s 815us/step - loss: 0.0052
Epoch 1408/1500
4/4 [==============================] - 0s 250us/step - loss: 0.0052
Epoch 1409/1500
4/4 [==============================] - 0s 852us/step - loss: 0.0052
Epoch 1410/1500
4/4 [==============================] - 0s 524us/step - loss: 0.0

Epoch 1498/1500
4/4 [==============================] - 0s 635us/step - loss: 0.0045
Epoch 1499/1500
4/4 [==============================] - 0s 954us/step - loss: 0.0045
Epoch 1500/1500
4/4 [==============================] - 0s 0us/step - loss: 0.0045


In [32]:
#Get predictions
model.predict(X)

array([[0.06083009],
       [0.93365234],
       [0.93703735],
       [0.07616138]], dtype=float32)